### ISSUE TITLE
online handwriting format

### ISSUE THREAD

**Issue by Cydiater** [AI-FREE-Team/Traditional-Chinese-Handwriting-Dataset#2]
Hi there, thanks for releasing the dataset. I am just wondering if there is any chance you can release the **online format** of the dataset. By online, I mean the dataset that contains the specific point and order of each character. We already have an online simplified Chinese handwriting dataset [here](http://www.nlpr.ia.ac.cn/databases/handwriting/Home.html). It would be very helpful to have an online traditional Chinese handwriting dataset to extend many tasks from simplified Chinese to traditional.

**Comment by chenkenanalytic** [comment]
Hi @Cydiater, thanks for your suggestions! The original data consists of every strokes for each character. You can find the resource [here](https://scidm.nchc.org.tw/dataset/stusteecs_chinese_mnist). The original format is xml which are composed of timestamps, strokes, and coordinates in (1000,1000) matrix. Hope it is what you need.

 Since I am not the original author of the project, it is not suitable for me to publish the data here on github.
